-- Development/testing sample data only.
-- These rows do not represent verified real provider coverage.

insert into public.providers (
  id,
  provider_name,
  slug,
  service_types,
  description,
  areas_covered,
  languages_spoken,
  phone,
  email,
  website_url,
  address_line,
  city,
  pricing_range,
  established_year,
  staff_count_range,
  is_verified,
  listing_tier,
  is_active,
  lead_email,
  lead_whatsapp
) values
(
  '10000000-0000-4000-8000-000000000001',
  'Sample Hyderabad Home Care Demo',
  'sample-hyderabad-home-care-demo',
  array['home_care', 'companion']::text[],
  'Sample/demo listing for testing home care and companion support search in Hyderabad.',
  array['Banjara Hills', 'Jubilee Hills', 'Madhapur']::text[],
  array['Telugu', 'Hindi', 'English']::text[],
  '+91 00000 10001',
  'sample-hyderabad-home-care@example.com',
  'https://example.com/sample-hyderabad-home-care-demo',
  'Sample demo address, Banjara Hills',
  'Hyderabad',
  'mid',
  2019,
  '21-50',
  true,
  'standard',
  true,
  'sample-hyderabad-home-care-leads@example.com',
  '+91 00000 20001'
),
(
  '10000000-0000-4000-8000-000000000002',
  'Sample Hyderabad Senior Living Demo',
  'sample-hyderabad-senior-living-demo',
  array['senior_living', 'dementia_care']::text[],
  'Sample/demo listing for testing senior living and dementia care search in Hyderabad.',
  array['Gachibowli', 'Kukatpally', 'Secunderabad']::text[],
  array['Telugu', 'English']::text[],
  '+91 00000 10002',
  'sample-hyderabad-senior-living@test.local',
  null,
  'Sample demo address, Gachibowli',
  'Hyderabad',
  'premium',
  2016,
  '50+',
  true,
  'premium',
  true,
  'sample-hyderabad-senior-living-leads@test.local',
  '+91 00000 20002'
),
(
  '10000000-0000-4000-8000-000000000003',
  'Sample Bengaluru Home Care Demo',
  'sample-bengaluru-home-care-demo',
  array['home_care', 'physio']::text[],
  'Sample/demo listing for testing home care and physiotherapy search in Bengaluru.',
  array['Indiranagar', 'Whitefield', 'Jayanagar']::text[],
  array['Kannada', 'English', 'Hindi']::text[],
  '+91 00000 10003',
  'sample-bengaluru-home-care@example.com',
  null,
  'Sample demo address, Indiranagar',
  'Bengaluru',
  'mid',
  2020,
  '6-20',
  false,
  'free',
  true,
  'sample-bengaluru-home-care-leads@example.com',
  '+91 00000 20003'
),
(
  '10000000-0000-4000-8000-000000000004',
  'Sample Bengaluru Senior Living Demo',
  'sample-bengaluru-senior-living-demo',
  array['senior_living', 'companion']::text[],
  'Sample/demo listing for testing senior living and companion support search in Bengaluru.',
  array['Koramangala', 'Hebbal', 'Marathahalli']::text[],
  array['Kannada', 'English']::text[],
  '+91 00000 10004',
  'sample-bengaluru-senior-living@test.local',
  'https://example.com/sample-bengaluru-senior-living-demo',
  'Sample demo address, Koramangala',
  'Bengaluru',
  'premium',
  2015,
  '50+',
  true,
  'premium',
  true,
  'sample-bengaluru-senior-living-leads@test.local',
  '+91 00000 20004'
),
(
  '10000000-0000-4000-8000-000000000005',
  'Sample Chennai Home Nursing Demo',
  'sample-chennai-home-nursing-demo',
  array['home_care', 'geriatric_doctor']::text[],
  'Sample/demo listing for testing home nursing and geriatric doctor search in Chennai.',
  array['T Nagar', 'Adyar', 'Mylapore']::text[],
  array['Tamil', 'English']::text[],
  '+91 00000 10005',
  'sample-chennai-home-nursing@example.com',
  null,
  'Sample demo address, T Nagar',
  'Chennai',
  'mid',
  2018,
  '21-50',
  true,
  'standard',
  true,
  'sample-chennai-home-nursing-leads@example.com',
  '+91 00000 20005'
),
(
  '10000000-0000-4000-8000-000000000006',
  'Sample Chennai Day Care Demo',
  'sample-chennai-day-care-demo',
  array['day_care', 'companion']::text[],
  'Sample/demo listing for testing elder day care and companion search in Chennai.',
  array['Anna Nagar', 'Velachery', 'Tambaram']::text[],
  array['Tamil', 'English', 'Hindi']::text[],
  '+91 00000 10006',
  'sample-chennai-day-care@test.local',
  null,
  'Sample demo address, Anna Nagar',
  'Chennai',
  'budget',
  2021,
  '6-20',
  false,
  'free',
  true,
  'sample-chennai-day-care-leads@test.local',
  '+91 00000 20006'
),
(
  '10000000-0000-4000-8000-000000000007',
  'Sample Mumbai Elder Support Demo',
  'sample-mumbai-elder-support-demo',
  array['home_care', 'companion']::text[],
  'Sample/demo listing for testing elder support search in Mumbai.',
  array['Andheri', 'Bandra', 'Powai']::text[],
  array['Marathi', 'Hindi', 'English']::text[],
  '+91 00000 10007',
  'sample-mumbai-elder-support@example.com',
  'https://example.com/sample-mumbai-elder-support-demo',
  'Sample demo address, Andheri',
  'Mumbai',
  'premium',
  2014,
  '50+',
  true,
  'premium',
  true,
  'sample-mumbai-elder-support-leads@example.com',
  '+91 00000 20007'
),
(
  '10000000-0000-4000-8000-000000000008',
  'Sample Mumbai Senior Living Demo',
  'sample-mumbai-senior-living-demo',
  array['senior_living', 'dementia_care']::text[],
  'Sample/demo listing for testing senior living search in Mumbai.',
  array['Dadar', 'Thane', 'Borivali']::text[],
  array['Marathi', 'English']::text[],
  '+91 00000 10008',
  'sample-mumbai-senior-living@test.local',
  null,
  'Sample demo address, Dadar',
  'Mumbai',
  'mid',
  2017,
  '21-50',
  true,
  'standard',
  true,
  'sample-mumbai-senior-living-leads@test.local',
  '+91 00000 20008'
),
(
  '10000000-0000-4000-8000-000000000009',
  'Sample Pune Physio Demo',
  'sample-pune-physio-demo',
  array['physio', 'home_care']::text[],
  'Sample/demo listing for testing physiotherapy and home care search in Pune.',
  array['Kothrud', 'Baner', 'Viman Nagar']::text[],
  array['Marathi', 'Hindi', 'English']::text[],
  '+91 00000 10009',
  'sample-pune-physio@example.com',
  null,
  'Sample demo address, Kothrud',
  'Pune',
  'mid',
  2020,
  '6-20',
  false,
  'free',
  true,
  'sample-pune-physio-leads@example.com',
  '+91 00000 20009'
),
(
  '10000000-0000-4000-8000-000000000010',
  'Sample Pune Companion Care Demo',
  'sample-pune-companion-care-demo',
  array['companion', 'day_care']::text[],
  'Sample/demo listing for testing companion care and day care search in Pune.',
  array['Hinjewadi', 'Wakad', 'Hadapsar']::text[],
  array['Marathi', 'English']::text[],
  '+91 00000 10010',
  'sample-pune-companion-care@test.local',
  'https://example.com/sample-pune-companion-care-demo',
  'Sample demo address, Wakad',
  'Pune',
  'premium',
  2016,
  '21-50',
  true,
  'premium',
  true,
  'sample-pune-companion-care-leads@test.local',
  '+91 00000 20010'
),
(
  '10000000-0000-4000-8000-000000000011',
  'Sample Delhi Companion Care Demo',
  'sample-delhi-companion-care-demo',
  array['companion', 'home_care']::text[],
  'Sample/demo listing for testing companion care search in Delhi.',
  array['South Delhi', 'Saket', 'Lajpat Nagar']::text[],
  array['Hindi', 'English', 'Punjabi']::text[],
  '+91 00000 10011',
  'sample-delhi-companion-care@example.com',
  null,
  'Sample demo address, South Delhi',
  'Delhi',
  'mid',
  2019,
  '21-50',
  true,
  'standard',
  true,
  'sample-delhi-companion-care-leads@example.com',
  '+91 00000 20011'
),
(
  '10000000-0000-4000-8000-000000000012',
  'Sample Delhi Home Care Demo',
  'sample-delhi-home-care-demo',
  array['home_care', 'geriatric_doctor']::text[],
  'Sample/demo listing for testing home care and geriatric doctor search in Delhi.',
  array['Dwarka', 'Rohini', 'Karol Bagh']::text[],
  array['Hindi', 'English']::text[],
  '+91 00000 10012',
  'sample-delhi-home-care@test.local',
  null,
  'Sample demo address, Dwarka',
  'Delhi',
  'budget',
  2022,
  '1-5',
  false,
  'free',
  true,
  'sample-delhi-home-care-leads@test.local',
  '+91 00000 20012'
),
(
  '10000000-0000-4000-8000-000000000013',
  'Sample Kolkata Elder Support Demo',
  'sample-kolkata-elder-support-demo',
  array['home_care', 'companion']::text[],
  'Sample/demo listing for testing elder support search in Kolkata.',
  array['Salt Lake', 'New Town', 'Park Street']::text[],
  array['Bengali', 'Hindi', 'English']::text[],
  '+91 00000 10013',
  'sample-kolkata-elder-support@example.com',
  'https://example.com/sample-kolkata-elder-support-demo',
  'Sample demo address, Salt Lake',
  'Kolkata',
  'premium',
  2013,
  '50+',
  true,
  'premium',
  true,
  'sample-kolkata-elder-support-leads@example.com',
  '+91 00000 20013'
),
(
  '10000000-0000-4000-8000-000000000014',
  'Sample Kolkata Dementia Care Demo',
  'sample-kolkata-dementia-care-demo',
  array['dementia_care', 'senior_living']::text[],
  'Sample/demo listing for testing dementia care search in Kolkata.',
  array['Ballygunge', 'Howrah', 'New Town']::text[],
  array['Bengali', 'English']::text[],
  '+91 00000 10014',
  'sample-kolkata-dementia-care@test.local',
  null,
  'Sample demo address, Ballygunge',
  'Kolkata',
  'mid',
  2018,
  '21-50',
  true,
  'standard',
  true,
  'sample-kolkata-dementia-care-leads@test.local',
  '+91 00000 20014'
),
(
  '10000000-0000-4000-8000-000000000015',
  'Sample Ahmedabad Home Care Demo',
  'sample-ahmedabad-home-care-demo',
  array['home_care', 'physio']::text[],
  'Sample/demo listing for testing home care and physiotherapy search in Ahmedabad.',
  array['Navrangpura', 'Satellite', 'Bopal']::text[],
  array['Gujarati', 'Hindi', 'English']::text[],
  '+91 00000 10015',
  'sample-ahmedabad-home-care@example.com',
  null,
  'Sample demo address, Navrangpura',
  'Ahmedabad',
  'mid',
  2020,
  '6-20',
  false,
  'free',
  true,
  'sample-ahmedabad-home-care-leads@example.com',
  '+91 00000 20015'
),
(
  '10000000-0000-4000-8000-000000000016',
  'Sample Ahmedabad Geriatric Clinic Demo',
  'sample-ahmedabad-geriatric-clinic-demo',
  array['geriatric_doctor', 'day_care']::text[],
  'Sample/demo listing for testing geriatric doctor and day care search in Ahmedabad.',
  array['Maninagar', 'Satellite', 'Navrangpura']::text[],
  array['Gujarati', 'English']::text[],
  '+91 00000 10016',
  'sample-ahmedabad-geriatric-clinic@test.local',
  'https://example.com/sample-ahmedabad-geriatric-clinic-demo',
  'Sample demo address, Maninagar',
  'Ahmedabad',
  'premium',
  2015,
  '21-50',
  true,
  'premium',
  true,
  'sample-ahmedabad-geriatric-clinic-leads@test.local',
  '+91 00000 20016'
),
(
  '10000000-0000-4000-8000-000000000017',
  'Sample Lucknow Home Care Demo',
  'sample-lucknow-home-care-demo',
  array['home_care', 'companion']::text[],
  'Sample/demo listing for testing home care search in Lucknow.',
  array['Gomti Nagar', 'Hazratganj', 'Indira Nagar']::text[],
  array['Hindi', 'English']::text[],
  '+91 00000 10017',
  'sample-lucknow-home-care@example.com',
  null,
  'Sample demo address, Gomti Nagar',
  'Lucknow',
  'mid',
  2019,
  '6-20',
  true,
  'standard',
  true,
  'sample-lucknow-home-care-leads@example.com',
  '+91 00000 20017'
),
(
  '10000000-0000-4000-8000-000000000018',
  'Sample Lucknow Day Care Demo',
  'sample-lucknow-day-care-demo',
  array['day_care', 'geriatric_doctor']::text[],
  'Sample/demo listing for testing elder day care search in Lucknow.',
  array['Aliganj', 'Indira Nagar', 'Hazratganj']::text[],
  array['Hindi']::text[],
  '+91 00000 10018',
  'sample-lucknow-day-care@test.local',
  null,
  'Sample demo address, Aliganj',
  'Lucknow',
  'budget',
  2021,
  '1-5',
  false,
  'free',
  true,
  'sample-lucknow-day-care-leads@test.local',
  '+91 00000 20018'
),
(
  '10000000-0000-4000-8000-000000000019',
  'Sample Kochi Dementia Care Demo',
  'sample-kochi-dementia-care-demo',
  array['dementia_care', 'senior_living']::text[],
  'Sample/demo listing for testing dementia care search in Kochi.',
  array['Edappally', 'Kakkanad', 'Vyttila']::text[],
  array['Malayalam', 'English']::text[],
  '+91 00000 10019',
  'sample-kochi-dementia-care@example.com',
  'https://example.com/sample-kochi-dementia-care-demo',
  'Sample demo address, Edappally',
  'Kochi',
  'premium',
  2014,
  '50+',
  true,
  'premium',
  true,
  'sample-kochi-dementia-care-leads@example.com',
  '+91 00000 20019'
),
(
  '10000000-0000-4000-8000-000000000020',
  'Sample Kochi Home Care Demo',
  'sample-kochi-home-care-demo',
  array['home_care', 'physio']::text[],
  'Sample/demo listing for testing home care and physiotherapy search in Kochi.',
  array['Fort Kochi', 'Vyttila', 'Kakkanad']::text[],
  array['Malayalam', 'Hindi', 'English']::text[],
  '+91 00000 10020',
  'sample-kochi-home-care@test.local',
  null,
  'Sample demo address, Fort Kochi',
  'Kochi',
  'mid',
  2020,
  '6-20',
  true,
  'standard',
  true,
  'sample-kochi-home-care-leads@test.local',
  '+91 00000 20020'
),
(
  '10000000-0000-4000-8000-000000000021',
  'Sample Bhubaneswar Elder Care Demo',
  'sample-bhubaneswar-elder-care-demo',
  array['home_care', 'companion']::text[],
  'Sample/demo listing for testing elder care search in Bhubaneswar.',
  array['Patia', 'Saheed Nagar', 'Khandagiri']::text[],
  array['Odia', 'Hindi', 'English']::text[],
  '+91 00000 10021',
  'sample-bhubaneswar-elder-care@example.com',
  null,
  'Sample demo address, Patia',
  'Bhubaneswar',
  'mid',
  2018,
  '21-50',
  true,
  'standard',
  true,
  'sample-bhubaneswar-elder-care-leads@example.com',
  '+91 00000 20021'
),
(
  '10000000-0000-4000-8000-000000000022',
  'Sample Bhubaneswar Physio Demo',
  'sample-bhubaneswar-physio-demo',
  array['physio', 'day_care']::text[],
  'Sample/demo listing for testing physiotherapy and day care search in Bhubaneswar.',
  array['Khandagiri', 'Patia', 'Saheed Nagar']::text[],
  array['Odia', 'English']::text[],
  '+91 00000 10022',
  'sample-bhubaneswar-physio@test.local',
  null,
  'Sample demo address, Khandagiri',
  'Bhubaneswar',
  'budget',
  2022,
  '1-5',
  false,
  'free',
  true,
  'sample-bhubaneswar-physio-leads@test.local',
  '+91 00000 20022'
),
(
  '10000000-0000-4000-8000-000000000023',
  'Sample Jaipur Senior Living Demo',
  'sample-jaipur-senior-living-demo',
  array['senior_living', 'dementia_care']::text[],
  'Sample/demo listing for testing senior living search in Jaipur.',
  array['Malviya Nagar', 'Vaishali Nagar', 'Mansarovar']::text[],
  array['Hindi', 'English']::text[],
  '+91 00000 10023',
  'sample-jaipur-senior-living@example.com',
  'https://example.com/sample-jaipur-senior-living-demo',
  'Sample demo address, Malviya Nagar',
  'Jaipur',
  'premium',
  2012,
  '50+',
  true,
  'premium',
  true,
  'sample-jaipur-senior-living-leads@example.com',
  '+91 00000 20023'
),
(
  '10000000-0000-4000-8000-000000000024',
  'Sample Jaipur Companion Care Demo',
  'sample-jaipur-companion-care-demo',
  array['companion', 'home_care']::text[],
  'Sample/demo listing for testing companion care search in Jaipur.',
  array['C Scheme', 'Mansarovar', 'Vaishali Nagar']::text[],
  array['Hindi']::text[],
  '+91 00000 10024',
  'sample-jaipur-companion-care@test.local',
  null,
  'Sample demo address, C Scheme',
  'Jaipur',
  'mid',
  2021,
  '6-20',
  false,
  'free',
  true,
  'sample-jaipur-companion-care-leads@test.local',
  '+91 00000 20024'
),
(
  '10000000-0000-4000-8000-000000000025',
  'Sample Indore Home Care Demo',
  'sample-indore-home-care-demo',
  array['home_care', 'physio']::text[],
  'Sample/demo listing for testing home care search in Indore.',
  array['Vijay Nagar', 'Palasia', 'Annapurna Road']::text[],
  array['Hindi', 'English']::text[],
  '+91 00000 10025',
  'sample-indore-home-care@example.com',
  null,
  'Sample demo address, Vijay Nagar',
  'Indore',
  'mid',
  2019,
  '21-50',
  true,
  'standard',
  true,
  'sample-indore-home-care-leads@example.com',
  '+91 00000 20025'
),
(
  '10000000-0000-4000-8000-000000000026',
  'Sample Indore Geriatric Care Demo',
  'sample-indore-geriatric-care-demo',
  array['geriatric_doctor', 'companion']::text[],
  'Sample/demo listing for testing geriatric doctor search in Indore.',
  array['Rau', 'Palasia', 'Vijay Nagar']::text[],
  array['Hindi']::text[],
  '+91 00000 10026',
  'sample-indore-geriatric-care@test.local',
  'https://example.com/sample-indore-geriatric-care-demo',
  'Sample demo address, Rau',
  'Indore',
  'premium',
  2016,
  '21-50',
  true,
  'premium',
  true,
  'sample-indore-geriatric-care-leads@test.local',
  '+91 00000 20026'
),
(
  '10000000-0000-4000-8000-000000000027',
  'Sample Guwahati Home Care Demo',
  'sample-guwahati-home-care-demo',
  array['home_care', 'companion']::text[],
  'Sample/demo listing for testing home care search in Guwahati.',
  array['Dispur', 'Beltola', 'Six Mile']::text[],
  array['Assamese', 'Hindi', 'English']::text[],
  '+91 00000 10027',
  'sample-guwahati-home-care@example.com',
  null,
  'Sample demo address, Dispur',
  'Guwahati',
  'mid',
  2020,
  '6-20',
  false,
  'free',
  true,
  'sample-guwahati-home-care-leads@example.com',
  '+91 00000 20027'
),
(
  '10000000-0000-4000-8000-000000000028',
  'Sample Guwahati Day Care Demo',
  'sample-guwahati-day-care-demo',
  array['day_care', 'geriatric_doctor']::text[],
  'Sample/demo listing for testing day care search in Guwahati.',
  array['Paltan Bazaar', 'Beltola', 'Dispur']::text[],
  array['Assamese', 'English']::text[],
  '+91 00000 10028',
  'sample-guwahati-day-care@test.local',
  'https://example.com/sample-guwahati-day-care-demo',
  'Sample demo address, Paltan Bazaar',
  'Guwahati',
  'premium',
  2017,
  '21-50',
  true,
  'premium',
  true,
  'sample-guwahati-day-care-leads@test.local',
  '+91 00000 20028'
)
on conflict (slug) do update set
  provider_name = excluded.provider_name,
  service_types = excluded.service_types,
  description = excluded.description,
  areas_covered = excluded.areas_covered,
  languages_spoken = excluded.languages_spoken,
  phone = excluded.phone,
  email = excluded.email,
  website_url = excluded.website_url,
  address_line = excluded.address_line,
  city = excluded.city,
  pricing_range = excluded.pricing_range,
  established_year = excluded.established_year,
  staff_count_range = excluded.staff_count_range,
  is_verified = excluded.is_verified,
  listing_tier = excluded.listing_tier,
  is_active = excluded.is_active,
  lead_email = excluded.lead_email,
  lead_whatsapp = excluded.lead_whatsapp;
