insert into public.providers (
  id,
  provider_name,
  slug,
  service_types,
  description,
  areas_covered,
  languages_spoken,
  phone,
  email,
  website_url,
  address_line,
  city,
  pricing_range,
  established_year,
  staff_count_range,
  is_verified,
  listing_tier,
  is_active,
  lead_email,
  lead_whatsapp
) values
(
  '11111111-1111-4111-8111-111111111111',
  'Sample Vizag Home Care Services',
  'sample-vizag-home-care',
  array['home_care', 'companion']::text[],
  'Sample provider offering hourly elder support, daily home care, and companionship visits across central Visakhapatnam.',
  array['MVP Colony', 'Dwaraka Nagar', 'Seethammadhara']::text[],
  array['Telugu', 'English', 'Hindi']::text[],
  '+91 90000 00001',
  'hello@samplevizaghomecare.test',
  'https://example.com/sample-vizag-home-care',
  'Sample address, MVP Colony',
  'Visakhapatnam',
  'mid',
  2018,
  '21-50',
  true,
  'premium',
  true,
  'leads@samplevizaghomecare.test',
  '+91 90000 10001'
),
(
  '22222222-2222-4222-8222-222222222222',
  'Sample Seaside Senior Living',
  'sample-seaside-senior-living',
  array['senior_living', 'dementia_care']::text[],
  'Sample assisted senior living facility with supervised routines and memory care support near the beach corridor.',
  array['Rushikonda', 'Bheemili', 'Madhurawada']::text[],
  array['Telugu', 'English']::text[],
  '+91 90000 00002',
  'care@sampleseasideseniorliving.test',
  'https://example.com/sample-seaside-senior-living',
  'Sample road, Rushikonda',
  'Visakhapatnam',
  'premium',
  2015,
  '50+',
  true,
  'premium',
  true,
  'leads@sampleseasideseniorliving.test',
  '+91 90000 10002'
),
(
  '33333333-3333-4333-8333-333333333333',
  'Sample Madhurawada Elder Day Care',
  'sample-madhurawada-day-care',
  array['day_care', 'companion']::text[],
  'Sample day care center for seniors needing daytime supervision, meals, activities, and assisted transport coordination.',
  array['Madhurawada', 'Rushikonda', 'MVP Colony']::text[],
  array['Telugu', 'English']::text[],
  '+91 90000 00003',
  'info@samplemadhurawadadaycare.test',
  null,
  'Sample layout, Madhurawada',
  'Visakhapatnam',
  'mid',
  2020,
  '6-20',
  false,
  'standard',
  true,
  'leads@samplemadhurawadadaycare.test',
  '+91 90000 10003'
),
(
  '44444444-4444-4444-8444-444444444444',
  'Sample Gajuwaka Physio At Home',
  'sample-gajuwaka-physio-at-home',
  array['physio', 'home_care']::text[],
  'Sample in-home physiotherapy and mobility support service for older adults recovering from illness or injury.',
  array['Gajuwaka', 'NAD', 'Anakapalle']::text[],
  array['Telugu', 'Hindi', 'English']::text[],
  '+91 90000 00004',
  'appointments@samplegajuwakaphysio.test',
  'https://example.com/sample-gajuwaka-physio',
  'Sample complex, Gajuwaka',
  'Visakhapatnam',
  'mid',
  2019,
  '6-20',
  true,
  'standard',
  true,
  'leads@samplegajuwakaphysio.test',
  '+91 90000 10004'
),
(
  '55555555-5555-4555-8555-555555555555',
  'Sample Siripuram Geriatric Clinic',
  'sample-siripuram-geriatric-clinic',
  array['geriatric_doctor', 'physio']::text[],
  'Sample outpatient geriatric consultation clinic with care planning and therapy referrals for senior patients.',
  array['Siripuram', 'Dwaraka Nagar', 'Akkayyapalem']::text[],
  array['Telugu', 'English']::text[],
  '+91 90000 00005',
  'frontdesk@samplesiripuramgeriatrics.test',
  'https://example.com/sample-siripuram-geriatrics',
  'Sample towers, Siripuram',
  'Visakhapatnam',
  'premium',
  2012,
  '21-50',
  true,
  'premium',
  true,
  'leads@samplesiripuramgeriatrics.test',
  '+91 90000 10005'
),
(
  '66666666-6666-4666-8666-666666666666',
  'Sample Pendurthi Companion Care',
  'sample-pendurthi-companion-care',
  array['companion', 'home_care']::text[],
  'Sample companion care provider for errands, daily check-ins, meal reminders, and non-medical elder support.',
  array['Pendurthi', 'NAD', 'Gajuwaka']::text[],
  array['Telugu']::text[],
  '+91 90000 00006',
  'care@samplependurthicompanion.test',
  null,
  'Sample street, Pendurthi',
  'Visakhapatnam',
  'budget',
  2021,
  '1-5',
  false,
  'free',
  true,
  'leads@samplependurthicompanion.test',
  '+91 90000 10006'
),
(
  '77777777-7777-4777-8777-777777777777',
  'Sample Seethammadhara Memory Care',
  'sample-seethammadhara-memory-care',
  array['dementia_care', 'senior_living']::text[],
  'Sample memory care and supervised senior living provider awaiting admin approval for public launch.',
  array['Seethammadhara', 'MVP Colony', 'Dwaraka Nagar']::text[],
  array['Telugu', 'English', 'Hindi']::text[],
  '+91 90000 00007',
  'hello@sampleseethammadharamemory.test',
  null,
  'Sample avenue, Seethammadhara',
  'Visakhapatnam',
  'premium',
  2017,
  '21-50',
  true,
  'standard',
  false,
  'leads@sampleseethammadharamemory.test',
  '+91 90000 10007'
),
(
  '88888888-8888-4888-8888-888888888888',
  'Sample Anakapalle Elder Support',
  'sample-anakapalle-elder-support',
  array['home_care', 'day_care']::text[],
  'Sample elder support provider under review for home visits and day supervision in the extended launch area.',
  array['Anakapalle', 'Gajuwaka', 'Pendurthi']::text[],
  array['Telugu', 'Hindi']::text[],
  '+91 90000 00008',
  'team@sampleanakapalleelder.test',
  null,
  'Sample center, Anakapalle',
  'Visakhapatnam',
  'budget',
  2022,
  '6-20',
  false,
  'free',
  false,
  'leads@sampleanakapalleelder.test',
  '+91 90000 10008'
),
(
  '99999999-9999-4999-8999-999999999999',
  'Sample Akkayyapalem Day Support',
  'sample-akkayyapalem-day-support',
  array['day_care', 'geriatric_doctor']::text[],
  'Sample senior day support center with periodic geriatric doctor visits and family care coordination.',
  array['Akkayyapalem', 'Dwaraka Nagar', 'Siripuram']::text[],
  array['Telugu', 'English']::text[],
  '+91 90000 00009',
  'support@sampleakkayyapalemday.test',
  'https://example.com/sample-akkayyapalem-day-support',
  'Sample junction, Akkayyapalem',
  'Visakhapatnam',
  'mid',
  2016,
  '6-20',
  true,
  'standard',
  true,
  'leads@sampleakkayyapalemday.test',
  '+91 90000 10009'
),
(
  'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  'Sample NAD Night Nursing',
  'sample-nad-night-nursing',
  array['home_care', 'dementia_care']::text[],
  'Sample overnight nursing and dementia support service for families needing monitored elder care at home.',
  array['NAD', 'Gajuwaka', 'Pendurthi', 'MVP Colony']::text[],
  array['Telugu', 'English', 'Hindi']::text[],
  '+91 90000 00010',
  'nightcare@samplenadnursing.test',
  null,
  'Sample main road, NAD',
  'Visakhapatnam',
  'premium',
  2014,
  '21-50',
  true,
  'premium',
  true,
  'leads@samplenadnursing.test',
  '+91 90000 10010'
)
on conflict (slug) do update set
  provider_name = excluded.provider_name,
  service_types = excluded.service_types,
  description = excluded.description,
  areas_covered = excluded.areas_covered,
  languages_spoken = excluded.languages_spoken,
  phone = excluded.phone,
  email = excluded.email,
  website_url = excluded.website_url,
  address_line = excluded.address_line,
  city = excluded.city,
  pricing_range = excluded.pricing_range,
  established_year = excluded.established_year,
  staff_count_range = excluded.staff_count_range,
  is_verified = excluded.is_verified,
  listing_tier = excluded.listing_tier,
  is_active = excluded.is_active,
  lead_email = excluded.lead_email,
  lead_whatsapp = excluded.lead_whatsapp;
